#include "ringbuffer.h"
#include <math.h>
struct Config{ float base_thr; float k_ema; int dead_time_us; int min_pos_hits; float penalty_w; bool output_raw; float ref_lat, ref_lon; float ema_alpha; float dyn_k; int min_pos_hits_per_win; int pre_strict_tol; int short_min_samp; int long_max_samp; };
SampleFifo g_samp[3];
static CorrCfg cfg_from(const struct Config &cfg){ CorrCfg c; c.preamble_len_samp=160; c.bit_samp=20; c.halfbit_samp=10; c.short_min=cfg.short_min_samp; c.long_max=cfg.long_max_samp; return c; }
void init_corr_state(CorrState &st, const struct Config &cfg){ st.base_thr=cfg.base_thr; st.k=cfg.k_ema; st.ema_noise=0.0f; st.dead_until=0; }
static inline uint8_t sget(int ch, uint32_t idx){ return g_samp[ch].s[idx & (SAMPLE_FIFO_SIZE-1)]; }
static int correlate_preamble(int ch, uint32_t cur, const CorrCfg &ccfg, const struct Config &cfg, float &score, int &t0_offset){ const int centers[6]={0,10,20,70,80,110}; const int win=3; int best_off=-1; float best_score=-1e9; for(int shift=-4; shift<=4; ++shift){ int t0=(int)cur - ccfg.preamble_len_samp + shift; if(t0<0) continue; float posHits=0.0f; int penalties=0; bool longPulse=false; bool perwin_ok=true; int cpos[6]; for(int k=0;k<6;k++) cpos[k]=t0+centers[k]; if (abs((cpos[1]-cpos[0]) - 20) > cfg.pre_strict_tol) continue; if (abs((cpos[2]-cpos[1]) - 50) > cfg.pre_strict_tol) continue; if (abs((cpos[3]-cpos[2]) - 20) > cfg.pre_strict_tol) continue; for(int k=0;k<6;k++){ int c=cpos[k]; int hits=0; for(int d=-win; d<=win; ++d) hits += sget(ch, c+d); if(hits < cfg.min_pos_hits_per_win){ perwin_ok=false; break;} posHits += hits; if(k<5){ int mid = t0 + (centers[k]+centers[k+1])/2; int off=0; for(int d=-win; d<=win; ++d) off += sget(ch, mid+d); penalties += off; } } if(!perwin_ok) continue; int run=0; for(int s=0;s<ccfg.preamble_len_samp;s++){ if(sget(ch,t0+s)){ run++; if(run>ccfg.long_max){ longPulse=true; break; } } else run=0; } if(longPulse) continue; float sc = posHits - cfg.penalty_w * penalties; if(sc>best_score){ best_score=sc; best_off=t0; } } if(best_off<0) return 0; score=best_score; t0_offset=best_off; return 1; }
static bool decode_bits_from_samples(int ch, uint32_t t0, const CorrCfg &ccfg, const struct Config &cfg, RawMessage &rm){ int start=t0+ccfg.preamble_len_samp; int max_bits=112; uint8_t bits[120]={0}; for(int b=0;b<max_bits;b++){ int bit_base=start + b*ccfg.bit_samp; int a=0,bh=0; for(int d=0; d<ccfg.halfbit_samp; ++d) a += sget(ch, bit_base+d); for(int d=0; d<ccfg.halfbit_samp; ++d) bh += sget(ch, bit_base+ccfg.halfbit_samp+d); bits[b] = (a>bh)?1:0; }
  int msg_bits=112, msg_bytes=14; int energy_after_56=0; for(int i=56;i<112;i++) energy_after_56 += bits[i]; if(energy_after_56 < 3){ msg_bits=56; msg_bytes=7; }
  memset(rm.payload,0,sizeof(rm.payload)); for(int i=0;i<msg_bits;i++){ int byte=i>>3; int bit=7-(i&7); if(bits[i]) rm.payload[byte] |= (1<<bit);} rm.bits=msg_bits; rm.bytes=msg_bytes; rm.t0_us=(uint32_t)((t0*50)/1000); return true; }
int run_correlator_and_slice(int ch, const struct Config &cfg, LockFreePacketQueue &outq){ static uint32_t last_t0_samp[3]={0,0,0}; static float ema_noise[3]={0,0,0}; CorrCfg ccfg=cfg_from(cfg); uint32_t widx=g_samp[ch].widx; if ((int32_t)(widx - last_t0_samp[ch]) < (int32_t)(cfg.dead_time_us * 20)) return 0; float score=0; int t0=0; int ok=correlate_preamble(ch, widx, ccfg, cfg, score, t0); if(!ok){ ema_noise[ch] = (1.0f-cfg.ema_alpha)*ema_noise[ch] + cfg.ema_alpha*1.0f; return 0;} float dyn_thr = cfg.base_thr + cfg.dyn_k * ema_noise[ch]; if(score < dyn_thr){ ema_noise[ch] = (1.0f-cfg.ema_alpha)*ema_noise[ch] + cfg.ema_alpha*score; return 0; } RawMessage rm; rm.channel=ch; if(!decode_bits_from_samples(ch, t0, ccfg, cfg, rm)) return 0; last_t0_samp[ch]=widx; if(!outq.push(rm)){ /* drop */ } return 1; }
